version: "3.8"

networks:
  service:
    external: true
  data:
    external: true

volumes:
  data_images:

services:

  api:
    build:
      context: .
      dockerfile: ./appliance/api/Dockerfile
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
        - service
        - data
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - data_images:/srv/data/images
      - ./appliance/api:/opt/phex/api
      - ./packages/core/phexcore:/venv/lib/python3.10/site-packages/phexcore
      - ./packages/security/phexsec:/venv/lib/python3.10/site-packages/phexsec
