version: "3.8"

networks:
  dmz:
    external: true
  service:
    external: true

services:

  gateway:
    build: ./appliance/gateway
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      dmz:
      service:
        aliases:
          - "identity.phex.space"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      dmz:
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

